import { ReactNode } from 'react';
import { useGameStore } from '@store/gameStore';
import { AIRCRAFT_DATABASE } from '@data/aircraft';
import { formatFlightTime } from '@/utils/routeEngine';
import { DAY_LABELS, formatMinutes } from '@/utils/timetable';
import { CalendarClock, Map as MapIcon, Plane } from 'lucide-react';
import type { Route, TimetableLeg } from '@/types/game';

/**
 * Weekly timetable - every scheduled cycle of every route with hub-local
 * departure/arrival times (times are generated by utils/timetable when a route
 * is created/updated and for older saves on load).
 */
export function TimetableScreen() {
  const airline = useGameStore((state) => state.airline);
  const navigateTo = useGameStore((state) => state.navigateTo);

  if (!airline) return null;

  const routes = airline.routes;
  const activeRoutes = routes.filter((r) => r.isActive);
  const weeklyFlights = routes.reduce((sum, r) => sum + (r.timetable?.legs.length ?? 0), 0);
  const dailyFlights = Math.round(weeklyFlights / 7);
  const hubIata = airline.headquarters;

  // All legs bucketed by day (0=Mon .. 6=Sun), sorted by departure time.
  const legsByDay: TimetableLeg[][] = DAY_LABELS.map(() => []);
  for (const route of routes) {
    for (const leg of route.timetable?.legs ?? []) {
      legsByDay[leg.dayIndex % 7].push(leg);
    }
  }
  for (const day of legsByDay) day.sort((a, b) => a.departureMin - b.departureMin);

  // Flight numbers encode the route's sequence (route 1 -> 101/102/...): map back to the route.
  const seqToRoute = new Map<number, Route>(
    routes.filter((r) => r.timetable).map((r): [number, Route] => [r.timetable!.routeSeq, r])
  );
  const routeForLeg = (leg: TimetableLeg): Route | undefined =>
    seqToRoute.get(Math.floor(parseInt(leg.flightNumber, 10) / 100));
  const aircraftName = (route: Route | undefined): string =>
    (route ? AIRCRAFT_DATABASE.find((t) => t.id === route.aircraftId)?.name : undefined) ?? '-';

  return (
    <div className="h-full overflow-auto p-6 space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-2.5">
            <CalendarClock className="w-6 h-6 text-sky-400" />
            Weekly Timetable
          </h1>
          <p className="text-sm text-runway-400 mt-1">
            All departure &amp; arrival times in{' '}
            <span className="text-sky-400 font-semibold">{hubIata} local time</span> - first departure each day at{' '}
            {formatMinutes(6 * 60 + 30)}
          </p>
        </div>
        <button onClick={() => navigateTo('routes')} className="btn-primary flex items-center gap-2 shrink-0">
          <MapIcon className="w-4 h-4" />
          Manage Routes
        </button>
      </div>

      {/* Summary */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {[
          { label: 'Flights scheduled / week', value: String(weeklyFlights) },
          { label: 'Active routes', value: String(activeRoutes.length) },
          { label: 'Average flights / day', value: String(dailyFlights) },
        ].map((s) => (
          <div key={s.label} className="glass-panel p-5">
            <p className="text-2xl font-bold text-white">{s.value}</p>
            <p className="text-xs text-runway-400 mt-1">{s.label}</p>
          </div>
        ))}
      </div>

      {routes.length === 0 ? (
        <div className="glass-panel p-12 flex flex-col items-center justify-center text-center">
          <Plane className="w-12 h-12 text-runway-500 mb-4" />
          <h2 className="text-lg font-semibold text-white mb-2">No routes yet</h2>
          <p className="text-sm text-runway-400 mb-4">
            Create your first route and its weekly timetable will appear here.
          </p>
          <button onClick={() => navigateTo('routes')} className="btn-primary flex items-center gap-2">
            <MapIcon className="w-4 h-4" />
            Create First Route
          </button>
        </div>
      ) : (
        <>
          {/* Column legend */}
          <div className="flex items-center gap-3 text-[11px] text-runway-500 px-1">
            <span className="font-semibold text-runway-400">Columns:</span>
            <span>Flight #</span>
            <span>Dep</span>
            <span>Leg</span>
            <span>Arr</span>
            <span className="ml-auto">Block time</span>
          </div>

          {/* Day grid */}
          <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-4">
            {DAY_LABELS.map((label, day) => {
              const dayLegs = legsByDay[day];
              const items: ReactNode[] = [];
              let lastSeq = -1;
              let headerCount = 0;
              for (const leg of dayLegs) {
                const seq = Math.floor(parseInt(leg.flightNumber, 10) / 100);
                const route = routeForLeg(leg);
                if (seq !== lastSeq) {
                  lastSeq = seq;
                  headerCount += 1;
                  items.push(
                    <div key={`h-${seq}-${headerCount}`} className="flex items-center gap-2 pt-1.5 first:pt-0">
                      <MapIcon className="w-3 h-3 text-sky-400 shrink-0" />
                      <span className="text-xs font-semibold text-sky-300 truncate">
                        {route ? `${route.origin} -> ${route.destination}` : `Route ${seq}`}
                      </span>
                      <span className="text-[11px] text-runway-400 truncate">{aircraftName(route)}</span>
                      {route && !route.isActive && (
                        <span className="text-[10px] text-amber-400 shrink-0">Paused</span>
                      )}
                    </div>
                  );
                }
                const paused = route ? !route.isActive : false;
                items.push(
                  <div
                    key={`${leg.flightNumber}-${leg.fromIata}`}
                    className={`flex items-center gap-2 text-xs pl-4 ${paused ? 'opacity-50' : ''}`}
                  >
                    <span className="font-mono font-semibold text-white min-w-[3.4rem]">
                      {airline.iataCode}
                      {leg.flightNumber}
                    </span>
                    <span className="font-mono text-sky-300 w-10">{formatMinutes(leg.departureMin)}</span>
                    <span className="text-runway-300 min-w-[3.8rem] truncate">
                      {leg.fromIata} {'=>'} {leg.toIata}
                    </span>
                    <span className="font-mono text-runway-300 w-10">{formatMinutes(leg.arrivalMin)}</span>
                    <span className="text-runway-500 ml-auto whitespace-nowrap">
                      {formatFlightTime(leg.durationMin)}
                    </span>
                  </div>
                );
              }
              return (
                <div key={label} className="glass-panel p-4">
                  <div className="flex items-center justify-between mb-3">
                    <h2 className="text-sm font-bold text-white">{label}</h2>
                    <span className="text-xs text-runway-400">{dayLegs.length} flights</span>
                  </div>
                  {dayLegs.length === 0 ? (
                    <p className="text-xs text-runway-500">No scheduled flights.</p>
                  ) : (
                    <div className="space-y-1">{items}</div>
                  )}
                </div>
              );
            })}
          </div>
        </>
      )}
    </div>
  );
}